function ConvertTo-M365TRLocalizedText {
    <#
    .SYNOPSIS
    Exact-match PL->EN translation for the fixed strings collectors put into report data: column
    headers/property labels (e.g. 'Nazwa', 'Co robi'), full Section titles, and full Description
    sentences. Collectors always emit Polish text (single source of truth); this is the one place
    that turns it into English when the report language is 'en'. Unrecognized text is returned
    unchanged, so a label without a curated translation yet degrades to Polish instead of breaking.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][AllowEmptyString()][string]$Text,
        [ValidateSet('pl', 'en')][string]$Language = 'pl'
    )

    if ($Language -eq 'pl' -or [string]::IsNullOrEmpty($Text)) { return $Text }

    $map = Get-M365TRTranslationMap
    if ($map.ContainsKey($Text)) { return $map[$Text] }
    return $Text
}

function Get-M365TRTranslationMap {
    <#
    .SYNOPSIS
    The PL->EN dictionary backing ConvertTo-M365TRLocalizedText. Column-header/property labels
    and full Section/Description sentences share one flat lookup - they never collide since one
    is short single/double words and the other is full sentences. Extend this as new collectors
    are added or reworked; anything missing just falls back to the original Polish text.
    #>
    if ($script:M365TRTranslationMap) { return $script:M365TRTranslationMap }

    $script:M365TRTranslationMap = @{
        # ---- common column headers / property labels (short) ----
        'Nazwa'                    = 'Name'
        'Wartość'                  = 'Value'
        'Ustawienie'               = 'Setting'
        'Typ'                      = 'Type'
        'Opis'                     = 'Description'
        'Wydawca'                  = 'Publisher'
        'Platforma'                = 'Platform'
        'Platformy'                = 'Platforms'
        'Technologie'              = 'Technologies'
        'Stan'                     = 'State'
        'Status'                   = 'Status'
        'Domyślna'                 = 'Default'
        'Zweryfikowana'            = 'Verified'
        'Wbudowana'                = 'Built-in'
        'Co robi'                  = 'What it does'
        'Zmodyfikowano'            = 'Modified'
        'Utworzono'                = 'Created'
        'SzablonId'                = 'Template ID'
        'Kraj'                     = 'Country'
        'Domena podstawowa'        = 'Primary domain'
        'Identyfikator tenanta'    = 'Tenant ID'
        'Rola'                     = 'Role'
        'Członkowie'               = 'Members'
        'Licencja'                 = 'License'
        'Włączone'                 = 'Enabled'
        'Wyłączone'                = 'Disabled'
        'Tak'                      = 'Yes'
        'Nie'                      = 'No'
        'Brak'                     = 'None'
        'Wymagane'                 = 'Required'
        'Niewymagane'              = 'Not required'
        'Zablokowane'              = 'Blocked'
        'Dozwolone'                = 'Allowed'
        'Włączony'                 = 'Enabled'
        'Wyłączony'                = 'Disabled'
        'Niedozwolone'             = 'Not allowed'
        'Alfanumeryczny'           = 'Alphanumeric'
        'Numeryczny'               = 'Numeric'
        'Niski poziom zabezpieczeń' = 'Low security level'
        'Nieskonfigurowane'        = 'Not configured'

        # ---- shared Intune setting labels (Get-M365TRIntuneLabelMap) ----
        'Wymagane hasło/kod'                            = 'Password/passcode required'
        'Wymagany kod dostępu'                          = 'Passcode required'
        'Minimalna długość hasła'                       = 'Minimum password length'
        'Minimalna długość kodu'                        = 'Minimum passcode length'
        'Proste hasło'                                  = 'Simple password'
        'Prosty kod'                                    = 'Simple passcode'
        'Wymagany typ hasła'                            = 'Required password type'
        'Wymagany typ kodu'                             = 'Required passcode type'
        'Blokada ekranu po (min. bezczynności)'         = 'Screen lock after (min. of inactivity)'
        'Wygaszenie ekranu po (min.)'                   = 'Screen timeout after (min.)'
        'Ważność hasła (dni)'                           = 'Password expiration (days)'
        'Blokada powtórzenia ostatnich haseł (liczba)'  = 'Password history (count)'
        'Reset urządzenia po nieudanych próbach (liczba)' = 'Device reset after failed attempts (count)'
        'Szyfrowanie danych'                             = 'Data encryption'
        'Szyfrowanie BitLocker'                          = 'BitLocker encryption'
        'Wymagane szyfrowanie urządzenia'               = 'Device encryption required'
        'Urządzenia z jailbreak/root'                   = 'Jailbroken/rooted devices'
        'Ochrona przed zagrożeniami'                    = 'Threat protection'
        'Wymagany poziom ochrony'                       = 'Required protection level'
        'Minimalna wersja systemu'                      = 'Minimum OS version'
        'Maksymalna wersja systemu'                     = 'Maximum OS version'
        'Integralność kodu'                             = 'Code integrity'
        'Zapora sieciowa'                                = 'Firewall'
        'Blokada połączeń przychodzących (zapora)'      = 'Block inbound connections (firewall)'
        'Tryb ukryty zapory'                             = 'Firewall stealth mode'
        'Kamera'                                         = 'Camera'
        'Zrzuty ekranu'                                  = 'Screen capture'
        'Zrzuty ekranu w profilu służbowym'             = 'Screen capture in work profile'
        'Kamera w profilu służbowym'                    = 'Camera in work profile'
        'Powiadomienia przy zablokowanym ekranie'       = 'Notifications while device is locked'
        'Dodawanie kont w profilu służbowym'            = 'Adding accounts in work profile'
        'Udostępnianie kontaktów przez Bluetooth'       = 'Contact sharing over Bluetooth'
        'ID dzwoniącego między profilami'               = 'Cross-profile caller ID'
        'Wyszukiwanie kontaktów między profilami'       = 'Cross-profile contacts search'
        'Kopiuj-wklej między profilami'                 = 'Cross-profile copy-paste'
        'Udostępnianie danych między profilami'         = 'Cross-profile data sharing'
        'Domyślne uprawnienia aplikacji'                = 'Default app permissions'
        'Wymagany raport kondycji urządzenia'           = 'Device health attestation required'
        'Wymagany zarządzany profil poczty'             = 'Managed email profile required'
        'Debugowanie USB'                                = 'USB debugging'
        'Instalacja aplikacji spoza sklepu'             = 'Install apps from unknown sources'
        'Weryfikacja aplikacji (Google Play Protect)'   = 'App verification (Google Play Protect)'
        'Wymagane Google Play Services'                 = 'Google Play Services required'
        'Aktualne dostawcy zabezpieczeń'                = 'Up-to-date security providers'
        'Integralność aplikacji Company Portal'         = 'Company Portal app integrity'
        'Centrum sterowania na ekranie blokady'         = 'Control Center on lock screen'
        'Podgląd powiadomień na ekranie blokady'        = 'Notification preview on lock screen'
        'Widok "Dziś" na ekranie blokady'               = 'Today view on lock screen'
        'Ograniczenia wiekowe aplikacji'                = 'App age ratings'
        'Wymagany zabezpieczający moduł sprzętowy (TPM)' = 'Required hardware security module (TPM)'
        'Odblokowanie biometryczne'                     = 'Biometric unlock'
        'Remote Passport (logowanie z innego urządzenia)' = 'Remote Passport (sign-in from another device)'
        'Wielkie litery w kodzie PIN'                   = 'Uppercase letters in PIN'
        'Małe litery w kodzie PIN'                      = 'Lowercase letters in PIN'
        'Znaki specjalne w kodzie PIN'                  = 'Special characters in PIN'
        'Minimalna długość kodu PIN'                    = 'Minimum PIN length'
        'Maksymalna długość kodu PIN'                   = 'Maximum PIN length'
        'Ważność kodu PIN (dni)'                        = 'PIN expiration (days)'
        'Blokada powtórzenia ostatnich kodów PIN (liczba)' = 'PIN history (count)'
        'Rozszerzona biometria (Windows Hello)'         = 'Enhanced biometrics (Windows Hello)'
        'Instalacja aplikacji w tle podczas OOBE'       = 'Background app installation during OOBE'

        # ---- Mobile app detail fields (Intune.MobileApps) ----
        'Polecenie instalacji'                          = 'Install command'
        'Polecenie odinstalowywania'                    = 'Uninstall command'
        'Wymagane miejsce na dysku (MB)'                = 'Required disk space (MB)'
        'Wymagana pamięć fizyczna (MB)'                 = 'Required physical memory (MB)'
        'Minimalna liczba procesorów logicznych'        = 'Minimum number of logical processors'
        'Minimalna szybkość procesora CPU (MHz)'        = 'Minimum CPU speed (MHz)'
        'Adres URL sklepu App Store'                    = 'App Store URL'
        'Identyfikator pakietu'                         = 'Package ID'
        'Adres URL aplikacji'                            = 'App URL'
        'Architektura systemu operacyjnego'             = 'Operating system architecture'
        '(nieobsługiwany typ ustawienia)'               = '(unsupported setting type)'
        'Kody powrotne'                                  = 'Return codes'
        'Reguły wykrywania/wymagań'                     = 'Detection/requirement rules'
        'Nieznany typ'                                   = 'Unknown type'
        'Niestandardowy profil (macOS)'                 = 'Custom profile (macOS)'
        'Ogólne ustawienia urządzenia - profil służbowy Android' = 'General device settings - Android work profile'
        'Ogólne ustawienia urządzenia (iOS)'            = 'General device settings (iOS)'
        'Aktualizacje (iOS)'                             = 'Updates (iOS)'
        'Ogólne ustawienia urządzenia (macOS)'          = 'General device settings (macOS)'
        'Niestandardowy profil (Windows 10/11)'         = 'Custom profile (Windows 10/11)'
        'Ogólne ustawienia urządzenia (Windows 10/11)'  = 'General device settings (Windows 10/11)'

        # ---- EntraID.GroupSettings ----
        'Tworzenie grup Microsoft 365 dostępne dla wszystkich użytkowników' = 'Microsoft 365 group creation available to all users'
        'Grupa zabezpieczeń uprawniona do tworzenia grup (Id)' = 'Security group allowed to create groups (Id)'
        'Goście mogą być właścicielami grup'            = 'Guests can be group owners'
        'Goście mogą uzyskać dostęp do zawartości grup' = 'Guests can access group content'
        'Możliwość dodawania gości do grup'             = 'Ability to add guests to groups'
        'Link do wytycznych uzytkowania dla gości'      = 'Usage guidelines link for guests'
        'Link do wytycznych uzytkowania'                = 'Usage guidelines link'
        'Dostępne klasyfikacje grup'                    = 'Available group classifications'
        'Domyślna klasyfikacja nowej grupy'             = 'Default classification for new groups'
        'Standardowa lista zablokowanych słów (Microsoft)' = 'Standard blocked words list (Microsoft)'
        'Niestandardowa lista zablokowanych słów'       = 'Custom blocked words list'
        'Wymagany wzorzec nazwy (prefiks/sufiks)'       = 'Required naming pattern (prefix/suffix)'

        # ---- SharePoint.TenantSharingSettings ----
        'Poziom udostępniania zewnętrznego'             = 'External sharing level'
        'Ograniczenie udostępniania do wybranych domen' = 'Restrict sharing to selected domains'
        'Domeny dozwolone do udostępniania'             = 'Domains allowed for sharing'
        'Domeny zablokowane do udostępniania'           = 'Domains blocked from sharing'
        'Ponowne udostępnianie przez zaproszonych gości' = 'Resharing by invited guests'
        'Ponowne udostępnianie przez użytkowników zewnętrznych' = 'Resharing by external users'
        'Domyślny typ linku anonimowego dla plików'     = 'Default anonymous link type for files'
        'Domyślny typ linku anonimowego dla folderów'   = 'Default anonymous link type for folders'
        'Domyślny typ linku udostępniania'              = 'Default sharing link type'
        'Domyślne uprawnienia linku udostępniania'      = 'Default sharing link permission'
        'Śledzenie użytkowników korzystających z linków "Dowolna osoba"' = 'Tracking users of "Anyone" links'
        'Linki "Dowolna osoba" (anonimowe)'             = '"Anyone" (anonymous) links'
        'Wymagane ponowne potwierdzenie tożsamości (e-mail) dla gości' = 'Re-authentication (email) required for guests'
        'Częstotliwość ponownego potwierdzenia tożsamości gości (dni)' = 'Guest re-authentication frequency (days)'
        'Wygasanie dostępu gości zewnętrznych'          = 'External guest access expiration'
        'Dostęp gości wygasa po (dni)'                  = 'Guest access expires after (days)'
        'Tworzenie nowych witryn SharePoint'            = 'Creating new SharePoint sites'
        'Interfejs tworzenia witryn widoczny dla użytkowników' = 'Site creation UI visible to users'
        'Domyślna ścieżka zarządzana dla nowych witryn' = 'Default managed path for new sites'
        'Domyślny limit magazynu nowej witryny (MB)'    = 'Default storage limit for new sites (MB)'
        'Synchronizacja z niezarządzanych urządzeń'     = 'Sync from unmanaged devices'
        'Rozszerzenia plików wykluczone z synchronizacji' = 'File extensions excluded from sync'
        'Starsze (legacy) protokoły uwierzytelniania'   = 'Legacy authentication protocols'
        'Wymóg logowania tym samym kontem, które zaproszono' = 'Require sign-in with the same account that was invited'
        'Przechowywanie witryny OneDrive po usunięciu użytkownika (dni)' = 'OneDrive site retention after user deletion (days)'
        'Domyślny limit magazynu OneDrive (MB)'         = 'Default OneDrive storage limit (MB)'
        'Powiadomienia w aplikacji mobilnej SharePoint' = 'SharePoint mobile app notifications'
        'Kanał aktualności SharePoint'                  = 'SharePoint newsfeed'
        'Komentowanie stron witryny'                    = 'Commenting on site pages'
        'Synchronizacja OneDrive na macOS'              = 'OneDrive sync on macOS'
        'Automatyczne tagowanie obrazów (AI)'           = 'Automatic image tagging (AI)'
        'Wyłączone - brak udostępniania na zewnątrz'    = 'Disabled - no external sharing'
        'Tylko zaproszeni, zweryfikowani goście'        = 'Only invited, verified guests'
        'Zaproszeni goście oraz linki anonimowe'        = 'Invited guests and anonymous links'
        'Tylko już istniejący zaproszeni goście'        = 'Only existing invited guests'
        'Brak ograniczeń domenowych'                    = 'No domain restrictions'
        'Tylko dozwolone domeny'                        = 'Allowed domains only'
        'Wszystkie oprócz zablokowanych domen'          = 'All except blocked domains'
        'Brak (wybór przy każdym udostępnieniu)'        = 'None (choose each time when sharing)'
        'Bezpośredni dostęp (wskazani ludzie)'          = 'Direct access (specific people)'
        'Osoby w organizacji'                           = 'People in the organization'
        'Dowolna osoba z linkiem'                       = 'Anyone with the link'
        'Tylko odczyt'                                   = 'View only'
        'Edycja'                                         = 'Edit'

        # ---- EntraID.AuthorizationPolicy ----
        'Nikt (zapraszanie gości wyłączone)'            = 'No one (guest invitations disabled)'
        'Tylko administratorzy i wyznaczeni zapraszający' = 'Admins and designated inviters only'
        'Administratorzy, wyznaczeni zapraszający i wszyscy członkowie' = 'Admins, designated inviters, and all members'
        'Wszyscy użytkownicy (w tym goście)'            = 'All users (including guests)'
        'Taki sam dostęp jak członkowie (najbardziej permisywne)' = 'Same access as members (most permissive)'
        'Ograniczony dostęp do właściwości i członkostw innych obiektów katalogu (domyślne)' = 'Limited access to properties and memberships of other directory objects (default)'
        'Dostęp ograniczony do właściwości i członkostw własnych obiektów (najbardziej restrykcyjne)' = 'Access limited to properties and memberships of own objects (most restrictive)'
        'Kto może zapraszać gości'                      = 'Who can invite guests'
        'Poziom dostępu gości'                          = 'Guest access level'
        'Self-service reset hasła (SSPR)'               = 'Self-service password reset (SSPR)'
        'Zapisywanie się do subskrypcji e-mail (self-service sign-up)' = 'Email-based subscription sign-up (self-service)'
        'Dołączanie do organizacji po weryfikacji e-mail domeny' = 'Joining the organization after domain email verification'
        'Dostęp do starszego interfejsu MSOnline PowerShell' = 'Access to the legacy MSOnline PowerShell interface'
        'Użytkownicy mogą rejestrować aplikacje (app registrations)' = 'Users can register applications (app registrations)'
        'Użytkownicy mogą zakładać grupy zabezpieczeń'  = 'Users can create security groups'
        'Użytkownicy mogą odczytywać dane innych użytkowników' = "Users can read other users' data"
        'Użytkownicy mogą tworzyć nowe tenanty Entra ID' = 'Users can create new Entra ID tenants'

        # ---- Teams.FederationConfiguration ----
        'Federacja z innymi organizacjami Teams/Skype for Business' = 'Federation with other Teams/Skype for Business organizations'
        'Komunikacja z kontami prywatnymi Teams (konsumenckie)' = 'Communication with Teams consumer accounts'
        'Przychodzące zaproszenia od kont prywatnych Teams' = 'Inbound invitations from Teams consumer accounts'
        'Komunikacja z kontami Skype (publiczne, konsumenckie)' = 'Communication with Skype (public, consumer) accounts'
        'Ograniczenie kont prywatnych Teams do zweryfikowanych profili zewnętrznych' = 'Restrict Teams consumer accounts to verified external profiles'
        'Dozwolone domeny zewnętrzne'                   = 'Allowed external domains'
        'Zablokowane domeny zewnętrzne'                 = 'Blocked external domains'
        'Wszystkie znane domeny'                        = 'All known domains'
        'Dozwolona'                                      = 'Allowed'
        'Zablokowana'                                    = 'Blocked'

        # ---- EntraID.AuthenticationMethodsPolicy ----
        'Klucz bezpieczeństwa (FIDO2)'                  = 'Security key (FIDO2)'
        'Aplikacja Microsoft Authenticator'             = 'Microsoft Authenticator app'
        'Tymczasowy kod dostępu (TAP)'                  = 'Temporary Access Pass (TAP)'
        'Aplikacja uwierzytelniająca (Software OATH)'   = 'Authenticator app (Software OATH)'
        'Sprzetowy token OATH'                          = 'Hardware OATH token'
        'Połączenie głosowe'                             = 'Voice call'
        'E-mail (odzyskiwanie hasła)'                   = 'Email (password recovery)'
        'Certyfikat X.509'                               = 'X.509 certificate'
        'Verified ID (poświadczenia weryfikowalne)'     = 'Verified ID (verifiable credentials)'
        'Kod QR + PIN'                                   = 'QR code + PIN'

        # ---- Exchange.SafeAttachmentPolicies ----
        'Blokowanie wiadomości do czasu zakończenia analizy' = 'Block the message until analysis completes'
        'Usunięcie złośliwego załącznika, dostarczenie wiadomości bez niego' = 'Remove the malicious attachment, deliver the message without it'
        'Dostarczenie wiadomości bez oczekiwania na analizę (monitorowanie)' = 'Deliver the message without waiting for analysis (monitor)'
        'Natychmiastowe dostarczenie treści, załącznik dołączany po analizie' = 'Deliver content immediately, attachment added after analysis'
        'Monitorowanie - wiadomość dostarczana, wynik analizy tylko rejestrowany' = 'Monitor - message delivered, analysis result only logged'

        # ---- EntraID.CrossTenantAccessPolicy ----
        'Dozwolone chmury Microsoft'                    = 'Allowed Microsoft clouds'
        'Wszystkie (brak ograniczeń)'                   = 'All (no restrictions)'
        'Współpraca B2B - dostęp przychodzący (goście z innych tenantów u nas)' = 'B2B collaboration - inbound access (guests from other tenants with us)'
        'Współpraca B2B - dostęp wychodzący (nasi użytkownicy jako goście gdzie indziej)' = 'B2B collaboration - outbound access (our users as guests elsewhere)'
        'Bezpośrednie połączenie (Direct Connect) - przychodzące' = 'Direct Connect - inbound'
        'Bezpośrednie połączenie (Direct Connect) - wychodzące'   = 'Direct Connect - outbound'
        'Zaufanie do MFA zgłoszonego przez inny tenant'  = 'Trust MFA claimed by another tenant'
        'Zaufanie do zgodności urządzenia (Compliant Device) zgłoszonej przez inny tenant' = 'Trust device compliance claimed by another tenant'
        'Zaufanie do przyłączenia Hybrid Azure AD zgłoszonego przez inny tenant' = 'Trust Hybrid Azure AD Join claimed by another tenant'
        'Nieskonfigurowane (wartość domyślna Microsoft)' = 'Not configured (Microsoft default)'
        'Akceptowane od innych tenantów'                = 'Accepted from other tenants'
        'Nieakceptowane od innych tenantów'             = 'Not accepted from other tenants'

        # ---- missing ConvertTo-M365TRFriendlyConfigTypeName entries ----
        'Limit liczby rejestrowanych urządzeń'          = 'Device enrollment limit'
        'Ograniczenia platform przy rejestracji'        = 'Enrollment platform restrictions'
        'Strona kończąca rejestrację (Windows 10)'      = 'Enrollment completion page (Windows 10)'

        # ---- Purview.RightsManagementConfig ----
        'Usługa Azure RMS (szyfrowanie treści)'         = 'Azure RMS service (content encryption)'
        'Aktywowana'                                     = 'Activated'
        'Nieaktywowana'                                  = 'Not activated'
        'Licencjonowanie dla odbiorców wewnętrznych'    = 'Licensing for internal recipients'
        'Licencjonowanie dla odbiorców zewnętrznych'    = 'Licensing for external recipients'
        'Wyszukiwanie w zaszyfrowanych wiadomościach (indeksowanie)' = 'Search in encrypted messages (indexing)'
        'Odszyfrowywanie na potrzeby dziennika (Journal Report Decryption)' = 'Journal Report Decryption'
        'Dostęp super-użytkownika eDiscovery do zaszyfrowanej treści' = 'eDiscovery super user access to encrypted content'

        # ---- EntraID.SecureScore ----
        'WYNIK OGÓLNY'                                   = 'OVERALL SCORE'

        # ---- EntraID.OnPremisesSync ----
        'Wyłączona - tenant jest w pełni chmurowy (cloud-only), brak synchronizacji katalogu lokalnego.' = 'Disabled - the tenant is fully cloud-based (cloud-only), no on-premises directory sync.'
        'Włączona - tenant jest hybrydowy.'             = 'Enabled - the tenant is hybrid.'
        'Ostatnia synchronizacja'                        = 'Last synchronization'
        'Synchronizacja skrótów haseł (Password Hash Sync)' = 'Password Hash Sync'
        'Zapis zwrotny użytkowników (User Writeback)'   = 'User Writeback'
        'Zapis zwrotny urządzeń (Device Writeback)'     = 'Device Writeback'
        'Zapis zwrotny grup Microsoft 365 (Group Writeback)' = 'Microsoft 365 Group Writeback'
        'Synchronizacja UPN dla użytkowników zarządzanych w chmurze' = 'UPN synchronization for cloud-managed users'

        # ---- chapter sub-group titles (Get-M365TRSectionGroups) ----
        'Tożsamość i uwierzytelnianie'                  = 'Identity and authentication'
        'Administracja i uprawnienia'                    = 'Administration and permissions'
        'Organizacja i licencjonowanie'                  = 'Organization and licensing'
        'Governance i zgodność'                          = 'Governance and compliance'
        'Ocena zabezpieczeń'                              = 'Security assessment'
        'Rejestracja urządzeń'                            = 'Device enrollment'
        'Konfiguracja i zgodność urządzeń'               = 'Device configuration and compliance'
        'Aplikacje'                                       = 'Applications'
        'Role i administracja'                            = 'Roles and administration'
        'Ochrona poczty'                                  = 'Mail protection'
        'Przepływ poczty'                                 = 'Mail flow'
        'Etykiety poufności'                              = 'Sensitivity labels'
        'Zapobieganie utracie danych i retencja'         = 'Data loss prevention and retention'
        'Wymagane hasło po powrocie z bezczynności'     = 'Password required on return from idle'
        'Wczesne uruchamianie sterownika antymalware (ELAM)' = 'Early launch antimalware driver (ELAM)'
        'Polecana aplikacja'                            = 'Featured app'
        'Stan publikacji'                                = 'Publishing state'
        'Wersja zawartości'                              = 'Content version'
        'Nazwa pliku instalacyjnego'                    = 'Installer file name'
        'Ścieżka pliku instalacyjnego'                  = 'Installer file path'
        'Minimalna wersja Windows'                       = 'Minimum Windows version'

        # ---- App type friendly names (ConvertTo-M365TRFriendlyConfigTypeName) ----
        'Aplikacja systemu Windows (Win32)'             = 'Windows app (Win32)'
        'Aplikacje Microsoft 365 (Windows 10 i nowszy)' = 'Microsoft 365 Apps (Windows 10 and later)'
        'Aplikacja zarządzanego sklepu Google Play'     = 'Managed Google Play store app'
        'Aplikacja Google Play'                         = 'Google Play app'
        'Aplikacja biznesowa (Android)'                 = 'Line-of-business app (Android)'
        'Aplikacja App Store (iOS)'                     = 'App Store app (iOS)'
        'Aplikacja biznesowa (iOS)'                     = 'Line-of-business app (iOS)'
        'Aplikacja Apple Business Manager (VPP)'        = 'Apple Business Manager app (VPP)'
        'Aplikacja systemu macOS (PKG)'                 = 'macOS app (PKG)'
        'Aplikacja systemu macOS (DMG)'                 = 'macOS app (DMG)'
        'Aplikacja biznesowa (macOS)'                   = 'Line-of-business app (macOS)'
        'Aplikacje Microsoft 365 (macOS)'               = 'Microsoft 365 Apps (macOS)'
        'Aplikacja webowa (link)'                       = 'Web app (link)'
        'Aplikacja biznesowa MSI systemu Windows'       = 'Windows line-of-business app (MSI)'
        'Aplikacja AppX/MSIX'                           = 'AppX/MSIX app'
        'Aplikacja WinGet'                              = 'WinGet app'

        # ---- Conditional Access detail rows (Get-M365TRConditionalAccessRows) ----
        'Użytkownicy i grupy - dołącz: użytkownicy'     = 'Users and groups - include: users'
        'Użytkownicy i grupy - dołącz: grupy'           = 'Users and groups - include: groups'
        'Użytkownicy i grupy - dołącz: role katalogowe' = 'Users and groups - include: directory roles'
        'Użytkownicy i grupy - dołącz: goście/zewnętrzni' = 'Users and groups - include: guests/external users'
        'Użytkownicy i grupy - wyklucz: użytkownicy'    = 'Users and groups - exclude: users'
        'Użytkownicy i grupy - wyklucz: grupy'          = 'Users and groups - exclude: groups'
        'Użytkownicy i grupy - wyklucz: role katalogowe' = 'Users and groups - exclude: directory roles'
        'Użytkownicy i grupy - wyklucz: goście/zewnętrzni' = 'Users and groups - exclude: guests/external users'
        'Aplikacje w chmurze - dołącz'                  = 'Cloud apps - include'
        'Aplikacje w chmurze - wyklucz'                 = 'Cloud apps - exclude'
        'Akcje użytkownika'                              = 'User actions'
        'Konteksty uwierzytelniania'                    = 'Authentication contexts'
        'Platformy urządzeń - dołącz'                   = 'Device platforms - include'
        'Platformy urządzeń - wyklucz'                  = 'Device platforms - exclude'
        'Lokalizacje - dołącz'                           = 'Locations - include'
        'Lokalizacje - wyklucz'                          = 'Locations - exclude'
        'Typy aplikacji klienckich'                     = 'Client app types'
        'Poziom ryzyka logowania'                       = 'Sign-in risk level'
        'Poziom ryzyka użytkownika'                     = 'User risk level'
        'Filtr urządzeń'                                 = 'Device filter'
        'Kontrola dostępu'                               = 'Access control'
        'Wymagana siła uwierzytelniania'                = 'Required authentication strength'
        'Wymagane warunki korzystania'                  = 'Required terms of use'
        'Sesja - częstotliwość logowania'               = 'Session - sign-in frequency'
        'Sesja - trwałość przeglądarki'                 = 'Session - persistent browser'
        'Sesja - ograniczenia wymuszane przez aplikację' = 'Session - app-enforced restrictions'
        'Sesja - Cloud App Security'                    = 'Session - Cloud App Security'
        'Sesja - ciągła ocena dostępu'                  = 'Session - continuous access evaluation'
        'Sesja - domyślna odporność na awarie'          = 'Session - resilience defaults'
        'Blokuj dostęp'                                  = 'Block access'
        'Włączona'                                       = 'Enabled'
        'Wyłączona'                                      = 'Disabled'
        'Tylko raportowanie (report-only)'              = 'Report-only'

        # ---- detail-record (Podstawowe/Ustawienia/Przypisania) tables ----
        'Podstawowe'               = 'Basic information'
        'Ustawienia'               = 'Settings'
        'Przypisania'              = 'Assignments'
        'Tryb grupy'               = 'Assignment mode'
        'Grupa'                    = 'Group'
        'Filtruj'                  = 'Filter'
        'Tryb filtru'              = 'Filter mode'
        'Zawarte'                  = 'Included'
        'Wykluczone'               = 'Excluded'
        'Wszystkie urządzenia'     = 'All devices'
        'Wszyscy użytkownicy'      = 'All users'
        'Intencja'                 = 'Intent'

        # ---- Conditional Access ----
        'Warunki'                  = 'Conditions'
        'Użytkownicy i grupy'      = 'Users and groups'
        'Aplikacje w chmurze'      = 'Cloud apps'
        'Platformy urządzeń'      = 'Device platforms'
        'Lokalizacje'              = 'Locations'
        'Sesja'                    = 'Session'
        'Wymagaj MFA'              = 'Require MFA'
        'Przyznaj dostęp'          = 'Grant access'

        # ---- remaining property-name labels used across collectors ----
        'Priorytet'                             = 'Priority'
        'Kontrolka'                             = 'Control'
        'Kategoria'                             = 'Category'
        'Wynik'                                 = 'Score'
        'Domena'                                = 'Domain'
        'Typ obrazu'                            = 'Image type'
        'Ukryty'                                = 'Hidden'
        'Szczegóły'                             = 'Details'
        'Uprawnienie'                           = 'Permission'
        'SzablonRoli'                           = 'Role template'
        'TypUwierzytelniania'                   = 'Authentication type'
        'Akcja'                                 = 'Action'
        'Użytkownik'                            = 'User'
        'Widoczność'                            = 'Visibility'
        'Wolne'                                 = 'Available'
        'Wykupione'                             = 'Purchased'
        'Wymagana wersja systemu'               = 'Required OS version'
        'WymaganePrzejrzenie'                   = 'Review required'
        'ZakresKatalogu'                        = 'Directory scope'
        'Zaufana'                               = 'Trusted'
        'Zdehydratowana'                        = 'Dehydrated'
        'Urządzenia prywatne (BYOD)'            = 'Personal devices (BYOD)'
        'Rejestracja'                           = 'Enrollment'
        'StatusPolaczenia'                      = 'Connection status'
        'Aplikacja'                             = 'Application'
        'Data utworzenia'                       = 'Created date'
        'DostepAdminLokalny'                    = 'Local admin access'
        'Identyfikator uslug online'            = 'Online services ID'
        'SystemOperacyjny'                      = 'Operating system'
        'Metoda uwierzytelniania'               = 'Authentication method'
        'Nadano'                                = 'Granted'
        'Nazwa wyswietlana'                     = 'Display name'
        'OAuth2 włączony'                       = 'OAuth2 enabled'
        'Podmiot'                               = 'Principal'
        'Producent'                             = 'Manufacturer'
        'Protokoły z dozwolonym Basic Auth'     = 'Protocols with Basic Auth allowed'
        'Przypisane'                            = 'Assigned'
        'Reguła'                                = 'Rule'
        'MFA zarejestrowane'                    = 'MFA registered'

        # ---- Section titles / Descriptions (collectors) ----
        'Administratorzy uprzywilejowani i MFA' = 'Privileged administrators and MFA'
        'Aplikacje (service principals) z nadanymi uprawnieniami aplikacyjnymi wysokiego ryzyka (odczyt i zapis/pełna kontrola: *.ReadWrite.All, *.FullControl.All, *.ReadWrite.Directory, Mail.Send) na Microsoft Graph. Nie jest to pełna lista wszystkich aplikacji w tenancie - tylko te z uprawnieniami mogącymi modyfikować dane lub konfigurację.' = 'Applications (service principals) granted high-risk application permissions (read/write or full control: *.ReadWrite.All, *.FullControl.All, *.ReadWrite.Directory, Mail.Send) on Microsoft Graph. This is not a full list of every application in the tenant - only those with permissions that can modify data or configuration.'
        'Aplikacje mobilne' = 'Mobile apps'
        'Aplikacje mobilne opublikowane w Intune (Mobile Apps).' = 'Mobile apps published in Intune (Mobile Apps).'
        'Aplikacje z uprawnieniami aplikacyjnymi wysokiego ryzyka (zapis/pełna kontrola) na Microsoft Graph.' = 'Applications with high-risk application permissions (write/full control) on Microsoft Graph.'
        'Aplikacje z uprawnieniami wysokiego ryzyka' = 'Applications with high-risk permissions'
        'Bazowa ochrona tożsamości Microsoft (Security Defaults) - wymuszone MFA, blokada starych protokołów uwierzytelniania.' = "Microsoft's baseline identity protection (Security Defaults) - enforced MFA, legacy authentication protocols blocked."
        'Bazowa ochrona tożsamości Microsoft (Security Defaults) - wymuszone MFA, blokada starych protokołów uwierzytelniania. Wyklucza się wzajemnie z politykami Conditional Access.' = "Microsoft's baseline identity protection (Security Defaults) - enforced MFA, legacy authentication protocols blocked. Mutually exclusive with Conditional Access policies."
        'Bazowe konfiguracje zabezpieczeń (Security Baselines)' = 'Security Baselines'
        'Bazowe konfiguracje zabezpieczeń (Security Baselines) oraz inne intencje (intents) Intune.' = 'Security Baselines and other Intune intents.'
        'Brak niestandardowej konfiguracji ustawien grup Microsoft 365 w tym tenancie - obowiązują domyślne wartości Microsoft (m.in. tworzenie grup dostępne dla wszystkich użytkowników, goście nie mogą być właścicielami grup).' = "No custom Microsoft 365 group settings configuration in this tenant - Microsoft's default values apply (e.g. group creation available to all users, guests cannot be group owners)."
        'Czy usługa ochrony praw do informacji (Azure RMS) jest aktywowana na poziomie tenanta - warunek działania szyfrowania w etykietach poufności.' = 'Whether the Information Rights Management service (Azure RMS) is activated at the tenant level - a prerequisite for encryption in sensitivity labels.'
        'Definicje rol RBAC uzywanych do kontroli dostępu w Intune.' = 'RBAC role definitions used to control access in Intune.'
        'Domeny' = 'Domains'
        'Domeny akceptowane (Accepted Domains)' = 'Accepted Domains'
        'Domeny akceptowane skonfigurowane w Exchange Online.' = 'Accepted domains configured in Exchange Online.'
        'Domeny zarejestrowane i zweryfikowane w dzierzawie.' = 'Domains registered and verified in the tenant.'
        'Domyślne ustawienia dostępu między tenantami (Cross-Tenant Access) dla współpracy B2B - dotyczą wszystkich tenantów zewnętrznych, dla których nie skonfigurowano osobnych reguł.' = 'Default cross-tenant access settings for B2B collaboration - apply to all external tenants without dedicated rules configured.'
        'Domyślne ustawienia dostępu między tenantami (Cross-Tenant Access) dla współpracy B2B.' = 'Default cross-tenant access settings for B2B collaboration.'
        'Drukarki (Universal Print)' = 'Printers (Universal Print)'
        'Drukarki zarejestrowane w usludze Universal Print.' = 'Printers registered in Universal Print.'
        'Etykiety poufności (Sensitivity Labels)' = 'Sensitivity Labels'
        'Etykiety poufności skonfigurowane w Microsoft Purview.' = 'Sensitivity labels configured in Microsoft Purview.'
        'Etykiety retencji' = 'Retention labels'
        'Etykiety retencji skonfigurowane w Microsoft Purview.' = 'Retention labels configured in Microsoft Purview.'
        'Federacja z innymi organizacjami' = 'Federation with other organizations'
        'Filtry przypisań (Assignment Filters)' = 'Assignment Filters'
        'Filtry przypisań (Assignment Filters) używane do zawezania zakresu przypisań zasad.' = 'Assignment filters used to narrow the scope of policy assignments.'
        'Globalna konfiguracja organizacji Exchange Online.' = 'Global Exchange Online organization configuration.'
        'Informacja o tym, czy tenant jest zsynchronizowany z lokalnym Active Directory (hybrydowy) czy w pełni chmurowy, oraz jakie funkcje synchronizacji są włączone.' = 'Whether the tenant is synchronized with an on-premises Active Directory (hybrid) or fully cloud-based, and which sync features are enabled.'
        'Informacja o tym, czy tenant jest zsynchronizowany z lokalnym Active Directory (hybrydowy) czy w pełni chmurowy.' = 'Whether the tenant is synchronized with an on-premises Active Directory (hybrid) or fully cloud-based.'
        'Jednostki administracyjne' = 'Administrative units'
        'Jednostki administracyjne używane do delegowania administracji w Entra ID.' = 'Administrative units used to delegate administration in Entra ID.'
        'Konektory' = 'Connectors'
        'Konektory Universal Print.' = 'Universal Print connectors.'
        'Konektory przychodzące (Inbound Connectors)' = 'Inbound Connectors'
        'Konektory przychodzące skonfigurowane w Exchange Online.' = 'Inbound connectors configured in Exchange Online.'
        'Konektory wychodzące (Outbound Connectors)' = 'Outbound Connectors'
        'Konektory wychodzące skonfigurowane w Exchange Online.' = 'Outbound connectors configured in Exchange Online.'
        'Konfiguracja organizacji' = 'Organization configuration'
        'Konfiguracja polityki metod uwierzytelniania (MFA) w Entra ID.' = 'Authentication methods policy configuration (MFA) in Entra ID.'
        'Konfiguracje rejestracji urządzeń' = 'Device enrollment configurations'
        'Konfiguracje rejestracji urządzeń (Device Enrollment Configurations) w Intune.' = 'Device Enrollment Configurations in Intune.'
        'Które platformy urządzeń mogą się rejestrować w Intune, oraz czy urządzenia prywatne (BYOD) są dopuszczone - per zasada rejestracji.' = 'Which device platforms can enroll in Intune, and whether personal (BYOD) devices are allowed - per enrollment rule.'
        'Które platformy urządzeń mogą się rejestrować w Intune, oraz czy urządzenia prywatne (BYOD) są dopuszczone.' = 'Which device platforms can enroll in Intune, and whether personal (BYOD) devices are allowed.'
        'Licencje' = 'Licenses'
        'Licencje (SKU) wykupione i przypisane w tenancie.' = 'Licenses (SKUs) purchased and assigned in the tenant.'
        'Nazwane lokalizacje (Named Locations)' = 'Named Locations'
        'Nazwane lokalizacje (zakresy IP, kraje) wykorzystywane w politykach Conditional Access.' = 'Named locations (IP ranges, countries) used in Conditional Access policies.'
        'Niestandardowe zasady uwierzytelniania (blokada protokołów Basic Auth: POP3, IMAP4, SMTP AUTH, ActiveSync itd.) w Exchange Online. Brak takich zasad jest normalnym stanem - Microsoft domyślnie blokuje Basic Auth globalnie dla większości protokołów.' = 'Custom authentication policies (blocking Basic Auth protocols: POP3, IMAP4, SMTP AUTH, ActiveSync, etc.) in Exchange Online. Having none of these policies is a normal state - Microsoft blocks Basic Auth globally for most protocols by default.'
        'Niestandardowe zasady uwierzytelniania Exchange Online - które protokoły logowania Basic Auth (POP3, IMAP4, SMTP AUTH, ActiveSync itd.) są w nich jawnie dozwolone.' = 'Custom Exchange Online authentication policies - which Basic Auth sign-in protocols (POP3, IMAP4, SMTP AUTH, ActiveSync, etc.) are explicitly allowed in them.'
        'Obiekt konfiguracji grup istnieje, ale nie zawiera żadnych ustawien.' = 'The group configuration object exists but contains no settings.'
        'Obiekt ustawien istnieje, ale nie zawiera żadnych właściwości.' = 'The settings object exists but contains no properties.'
        'Obrazy urządzeń (Device Images) dostępne do wdrożenia na Cloud PC.' = 'Device Images available for deployment to Cloud PC.'
        'Obrazy urządzeń Cloud PC' = 'Cloud PC device images'
        'Ochrona praw do informacji (RMS/IRM)' = 'Rights Management (RMS/IRM)'
        'Ogolnotenantowe ustawienia dotyczące użytkowników i gości (zapraszanie, dostęp, domyślne uprawnienia).' = 'Tenant-wide settings for users and guests (invitations, access, default permissions).'
        'Ogolnotenantowe ustawienia dotyczące użytkowników i gości: zapraszanie, poziom dostępu, self-service oraz domyślne uprawnienia standardowego użytkownika.' = 'Tenant-wide settings for users and guests: invitations, access level, self-service, and default standard-user permissions.'
        'Ograniczenia rejestracji per platforma' = 'Enrollment restrictions per platform'
        'Ogólnotenantowa konfiguracja federacji Microsoft Teams z użytkownikami spoza organizacji.' = 'Tenant-wide Microsoft Teams federation configuration with users outside the organization.'
        'Organizacja' = 'Organization'
        'Pakiety dostępu (Access Packages) w ramach zarzadzania uprawnieniami (Entitlement Management).' = 'Access Packages under Entitlement Management.'
        'Podstawowe informacje o tenancie.' = 'Basic tenant information.'
        'Polityka dostępu między tenantami (Cross-Tenant Access)' = 'Cross-Tenant Access policy'
        'Polityka metod uwierzytelniania' = 'Authentication methods policy'
        'Polityki Conditional Access' = 'Conditional Access policies'
        'Polityki dostępu warunkowego (Conditional Access) skonfigurowane w Entra ID.' = 'Conditional Access policies configured in Entra ID.'
        'Polityki zgodności' = 'Compliance policies'
        'Polityki zgodności urządzeń (Compliance Policies) wymuszane przez Intune.' = 'Device Compliance Policies enforced by Intune.'
        'Połączenia on-premises (Cloud PC)' = 'On-premises connections (Cloud PC)'
        'Połączenia on-premises (Cloud PC) używane do laczenia Cloud PC z siecia firmowa.' = 'On-premises connections used to link Cloud PC to the corporate network.'
        'Profile Windows Autopilot' = 'Windows Autopilot profiles'
        'Profile konfiguracyjne urządzeń' = 'Device configuration profiles'
        'Profile konfiguracyjne urządzeń (Device Configuration Profiles) zarzadzane przez Intune.' = 'Device Configuration Profiles managed by Intune.'
        'Profile provisioningu' = 'Provisioning profiles'
        'Profile provisioningu Windows 365 Cloud PC.' = 'Windows 365 Cloud PC provisioning profiles.'
        'Profile wdrożenia Windows Autopilot używane przy rejestracji nowych urządzeń.' = 'Windows Autopilot deployment profiles used when enrolling new devices.'
        'Reguły przetwarzania poczty (mail flow) skonfigurowane w Exchange Online.' = 'Mail flow (transport) rules configured in Exchange Online.'
        'Reguły transportu (Transport Rules)' = 'Transport Rules'
        'Rejestrowanie zdarzeń (Unified Audit Log)' = 'Event logging (Unified Audit Log)'
        'Role RBAC w Intune' = 'RBAC roles in Intune'
        'Role katalogowe' = 'Directory roles'
        'Role katalogowe aktywne w dzierzawie Entra ID.' = 'Directory roles active in the Entra ID tenant.'
        'Skrypty PowerShell (Device Management Scripts)' = 'PowerShell scripts (Device Management Scripts)'
        'Skrypty PowerShell (Device Management Scripts) przypisane do urządzeń w Intune.' = 'PowerShell scripts (Device Management Scripts) assigned to devices in Intune.'
        'Stan rejestrowania zdarzeń w Unified Audit Log - warunek działania większości narzędzi śledczych i zgodności (Purview, eDiscovery, alerty).' = 'Unified Audit Log status - a prerequisite for most investigative and compliance tools (Purview, eDiscovery, alerts).'
        'Stan rejestrowania zdarzeń w Unified Audit Log.' = 'Unified Audit Log status.'
        'Synchronizacja z lokalnym Active Directory' = 'On-premises Active Directory synchronization'
        'Uprawnienia PIM (Privileged Identity Management)' = 'PIM (Privileged Identity Management) assignments'
        'Uprawnienia kwalifikowane (eligible) do rol uprzywilejowanych przyznane w ramach PIM.' = 'Eligible assignments to privileged roles granted through PIM.'
        'Ustawienia grup Microsoft 365' = 'Microsoft 365 group settings'
        'Ustawienia tworzenia, nazewnictwa i dostępu gości dla grup Microsoft 365 (Group.Unified).' = 'Creation, naming, and guest access settings for Microsoft 365 groups (Group.Unified).'
        'Ustawienia udostępniania (SharePoint/OneDrive)' = 'Sharing settings (SharePoint/OneDrive)'
        'Ustawienia udostępniania na poziomie tenanta dla SharePoint i OneDrive.' = 'Tenant-level sharing settings for SharePoint and OneDrive.'
        'Ustawienia udostępniania zewnętrznego, linków oraz tworzenia witryn na poziomie całego tenanta (SharePoint/OneDrive admin center > Zasady > Udostępnianie).' = 'Tenant-wide external sharing, link, and site-creation settings (SharePoint/OneDrive admin center > Policies > Sharing).'
        'Ustawienia użytkownika Cloud PC' = 'Cloud PC user settings'
        'Ustawienia użytkownika Cloud PC (Windows 365) dotyczące m.in. resetu i dostępu lokalnego administratora.' = 'Cloud PC (Windows 365) user settings covering, among others, reset and local administrator access.'
        'Ustawienia użytkowników i gości' = 'User and guest settings'
        'Uwierzytelnianie poczty (SPF / DKIM / DMARC)' = 'Email authentication (SPF / DKIM / DMARC)'
        'Użytkownicy posiadający uprzywilejowane role katalogowe (Global Administrator, Security Administrator itd.) oraz stan rejestracji MFA.' = 'Users holding privileged directory roles (Global Administrator, Security Administrator, etc.) and their MFA registration status.'
        'Użytkownicy posiadający uprzywilejowane role katalogowe oraz stan rejestracji MFA.' = 'Users holding privileged directory roles and their MFA registration status.'
        'Warunki korzystania (Terms of Use)' = 'Terms of Use'
        'Warunki korzystania (Terms of Use), które użytkownicy muszą zaakceptować.' = 'Terms of Use that users must accept.'
        'Weryfikacja publicznych rekordów DNS (SPF, DKIM, DMARC) dla domen pocztowych tenanta - dane pobrane bezpośrednio z publicznego DNS, nie z konfiguracji M365.' = "Verification of public DNS records (SPF, DKIM, DMARC) for the tenant's mail domains - data fetched directly from public DNS, not from M365 configuration."
        'Weryfikacja publicznych rekordów DNS (SPF, DKIM, DMARC) dla domen pocztowych tenanta.' = "Verification of public DNS records (SPF, DKIM, DMARC) for the tenant's mail domains."
        'Wynik Microsoft Secure Score oraz stan poszczególnych kontrolek zabezpieczeń - dane pobrane bezpośrednio z Microsoft, bez dodatkowej interpretacji.' = 'Microsoft Secure Score result and the state of individual security controls - data fetched directly from Microsoft, without additional interpretation.'
        'Wynik Microsoft Secure Score oraz stan poszczególnych kontrolek zabezpieczeń.' = 'Microsoft Secure Score result and the state of individual security controls.'
        'Zarządzanie uprawnieniami (Entitlement Management)' = 'Entitlement Management'
        'Zasady Anti-Malware' = 'Anti-Malware policies'
        'Zasady Anti-Phishing' = 'Anti-Phishing policies'
        'Zasady Anti-Spam (Content Filter)' = 'Anti-Spam policies (Content Filter)'
        'Zasady DLP (Data Loss Prevention)' = 'DLP policies (Data Loss Prevention)'
        'Zasady Safe Attachments (Defender for Office 365)' = 'Safe Attachments policies (Defender for Office 365)'
        'Zasady Safe Attachments (analiza załączników w piaskownicy) z Microsoft Defender for Office 365.' = 'Safe Attachments policies (sandbox attachment detonation) from Microsoft Defender for Office 365.'
        'Zasady Safe Links (Defender for Office 365)' = 'Safe Links policies (Defender for Office 365)'
        'Zasady Safe Links (skanowanie i przepisywanie linków) z Microsoft Defender for Office 365.' = 'Safe Links policies (link scanning and rewriting) from Microsoft Defender for Office 365.'
        'Zasady Settings Catalog' = 'Settings Catalog policies'
        'Zasady dostępu zewnętrznego' = 'External access policies'
        'Zasady dostępu zewnętrznego Microsoft Teams (federacja, konta prywatne, Azure Communication Services) per przypisanie.' = 'Microsoft Teams external access policies (federation, consumer accounts, Azure Communication Services) per assignment.'
        'Zasady etykiet poufności (Label Policies)' = 'Sensitivity label policies (Label Policies)'
        'Zasady filtrowania spamu skonfigurowane w Exchange Online.' = 'Spam filtering policies configured in Exchange Online.'
        'Zasady konfiguracji aplikacji (App Configuration Policies) dla aplikacji mobilnych.' = 'App Configuration Policies for mobile apps.'
        'Zasady konfiguracji aplikacji (App Configuration)' = 'App configuration policies (App Configuration)'
        'Zasady konfiguracji urządzeń mobilnych skonfigurowane w Exchange Online.' = 'Mobile device mailbox policies configured in Exchange Online.'
        'Zasady ochrony aplikacji (App Protection Policies) dla aplikacji zarzadzanych.' = 'App Protection Policies for managed apps.'
        'Zasady ochrony aplikacji (App Protection)' = 'App protection policies (App Protection)'
        'Zasady ochrony przed phishingiem skonfigurowane w Exchange Online.' = 'Anti-phishing policies configured in Exchange Online.'
        'Zasady ochrony przed zlosliwym oprogramowaniem skonfigurowane w Exchange Online.' = 'Anti-malware policies configured in Exchange Online.'
        'Zasady oparte na Settings Catalog konfigurujące ustawienia urządzeń.' = 'Settings Catalog-based policies configuring device settings.'
        'Zasady publikacji etykiet poufności skonfigurowane w Microsoft Purview - w tym domyślna etykieta i wymóg etykietowania (mandatory), jeśli skonfigurowane.' = 'Sensitivity label publishing policies configured in Microsoft Purview - including the default label and mandatory labeling requirement, if configured.'
        'Zasady publikacji etykiet poufności skonfigurowane w Microsoft Purview.' = 'Sensitivity label publishing policies configured in Microsoft Purview.'
        'Zasady retencji' = 'Retention policies'
        'Zasady retencji danych skonfigurowane w Microsoft Purview.' = 'Data retention policies configured in Microsoft Purview.'
        'Zasady spotkań' = 'Meeting policies'
        'Zasady spotkań Microsoft Teams (nagrywanie, transkrypcja, poczekalnia, czat, prezenterzy).' = 'Microsoft Teams meeting policies (recording, transcription, lobby, chat, presenters).'
        'Zasady udostępniania (Sharing Policies)' = 'Sharing Policies'
        'Zasady udostępniania kalendarza i danych skrzynek pocztowych skonfigurowane w Exchange Online.' = 'Calendar and mailbox data sharing policies configured in Exchange Online.'
        'Zasady urządzeń mobilnych (Mobile Device Mailbox Policies)' = 'Mobile Device Mailbox Policies'
        'Zasady uwierzytelniania (Basic Auth)' = 'Authentication policies (Basic Auth)'
        'Zasady wiadomości' = 'Messaging policies'
        'Zasady wiadomości Microsoft Teams (edycja/usuwanie, GIF-y, naklejki, podglądy linków, tłumaczenie).' = 'Microsoft Teams messaging policies (edit/delete, GIFs, stickers, link previews, translation).'
        'Zasady zapobiegania utracie danych (DLP) skonfigurowane w Microsoft Purview.' = 'Data Loss Prevention (DLP) policies configured in Microsoft Purview.'
    }
    return $script:M365TRTranslationMap
}
